TURAZE=/usr1/data/nrrobins/translation/onmt_corpora/tur_aze/
# files: aze-eng.azerbaijani  aze-eng.english  tur-eng.english  tur-eng.turkish
echo "BASE XPER'T %%%%%%"
python3 mt.py --out-dir tr-az --phon-type base --phon-pad zero --phon-gram 1 --src1 $TURAZE/aze-eng.azerbaijani --tgt1 $TURAZE/aze-eng.english --src2 $TURAZE/tur-eng.turkish --tgt2 $TURAZE/tur-eng.english --src1-lang hat --src2-lang fra --tgt-lang eng --train1-len 15000 --train2-len 250000 --val-len 5000 --test-len 5000 --config-temp config_template --mod-dim 512 --train-steps 60000 --save-steps 30000 --val-steps 5000 --spm-vocab-size 8000
echo "PHON RAND NGRAM XPER'T %%%%%%"
python3 mt.py --out-dir tr-az --phon-type phon --phon-pad rand --phon-gram 3 --src1 $TURAZE/aze-eng.azerbaijani --tgt1 $TURAZE/aze-eng.english --src2 $TURAZE/tur-eng.turkish --tgt2 $TURAZE/tur-eng.english --src1-lang hat --src2-lang fra --tgt-lang eng --train1-len 15000 --train2-len 250000 --val-len 5000 --test-len 5000 --config-temp config_template --mod-dim 512 --train-steps 60000 --save-steps 30000 --val-steps 5000 --spm-vocab-size 8000
echo "PHON RAND 1GRAM XPER'T %%%%%%"
python3 mt.py --out-dir tr-az --phon-type phon --phon-pad rand --phon-gram 1 --src1 $TURAZE/aze-eng.azerbaijani --tgt1 $TURAZE/aze-eng.english --src2 $TURAZE/tur-eng.turkish --tgt2 $TURAZE/tur-eng.english --src1-lang hat --src2-lang fra --tgt-lang eng --train1-len 15000 --train2-len 250000 --val-len 5000 --test-len 5000 --config-temp config_template --mod-dim 512 --train-steps 60000 --save-steps 30000 --val-steps 5000 --spm-vocab-size 8000
echo "PHON ZERO NGRAM XPER'T %%%%%%"
python3 mt.py --out-dir tr-az --phon-type phon --phon-pad zero --phon-gram 3 --src1 $TURAZE/aze-eng.azerbaijani --tgt1 $TURAZE/aze-eng.english --src2 $TURAZE/tur-eng.turkish --tgt2 $TURAZE/tur-eng.english --src1-lang hat --src2-lang fra --tgt-lang eng --train1-len 15000 --train2-len 250000 --val-len 5000 --test-len 5000 --config-temp config_template --mod-dim 512 --train-steps 60000 --save-steps 30000 --val-steps 5000 --spm-vocab-size 8000
